### ISSUE TITLE
Release 2.2.21 missing files

### ISSUE THREAD

**Issue by dkillick** [Unidata/UDUNITS-2#46]
The new release of UDUNITS2 (as available at `ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.21.tar.gz`) seems to be missing a couple of files that are needed by the Windows install process:

```
...

-- Configuring done

CMake Error at lib/CMakeLists.txt:62 (add_library):
  Cannot find source file:
    tsearch.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp .hxx .in .txx

CMake Error at prog/CMakeLists.txt:19 (add_executable):
  Cannot find source file:
    XGetOpt.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp .hxx .in .txx

...
```

We've encountered this in https://github.com/conda-forge/udunits2-feedstock/pull/9 and https://github.com/SciTools/conda-recipes-scitools/pull/227.

**Comment by ocefpaf** [comment]
Seems that  https://github.com/Unidata/UDUNITS-2/issues/32 resurfaced.

**Comment by semmerson** [comment]
The latest release (2.2.23) should fix this problem. Please let me know if it doesn't.

**Comment by dkillick** [comment]
Thanks muchly @semmerson! Still getting Windows build issues, but they don't seem to be related to missing files now

**Comment by ocefpaf** [comment]
@semmerson I can set a CI with AppVeyor, similar to https://github.com/Unidata/netcdf-c/pull/347, to test Windows build here and check this kind of failures. Let me know if you are interest and I will send a PR.

**Comment by semmerson** [comment]
@ocefpaf I'm interested.

**Comment by ocefpaf** [comment]
> @ocefpaf I'm interested.

Done in https://github.com/Unidata/UDUNITS-2/pull/47

BTW, latest `master` is passing :smile: Not sure what are the differences from the `2.2.23` tarball.

**Comment by ocefpaf** [comment]
@semmerson and @dkillick based on #47 and https://github.com/conda-forge/udunits2-feedstock/pull/9 latest `master` seems OK. Can we get a new tarball on GitHub based on `master` then?

**Comment by semmerson** [comment]
What do you mean? The tarball repository isn't GitHub; it's www.unidata.ucar.edu. Do you want a new tarball there? If so, is that necessary for testing the distribution with AppVeyor?

**Comment by ocefpaf** [comment]
> @ocefpaf What do you mean? The tarball repository isn't GitHub; it's www.unidata.ucar.edu.

We did had a few releases on GitHub. See https://github.com/Unidata/UDUNITS-2/releases
I kind of like to have the tarball on GitHub since that is closer to the source.

> Do you want a new tarball there?

That is fine as long as we figure out that is different from latest `master` and the previous `2.2.23` tarball from ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.23.tar.gz

> If so, is that necessary for testing the distribution with AppVeyor?

No. The AppVeyor testing is working. The tests are always against latest master and new PRs. What happened is that we saw latest `master` passing while the tarball from the ftp is not.

PS: You do need to enable AppVeyor on GitHub to get the pass/fail report in the PRs.

**Comment by semmerson** [comment]
@ocefpaf I'm not sure where those GitHub releases came from. I suggest you use `git archive --remote=https://github.com/Unidata/UDUNITS-2.git ...`, instead because it's guaranteed to **be** the source.

What's the URL for the AppVeyer facility?

**Comment by ocefpaf** [comment]
> What's the URL for the AppVeyer facility?

No URL. It gets it from the local code itself. See https://github.com/Unidata/UDUNITS-2/pull/47/files#diff-bd134fa847b11c75aba174f834eb80dfR8

**Comment by semmerson** [comment]
I don't understand. If the AppVeyer CI doesn't have a URL, then it can't be initiated via a GitHub webhook. And a search of GitHub help for the word "AppVeyer" yields nothing.

Please explain, in detail, what AppVeyer is, what it does, and how to use it.

**Comment by ocefpaf** [comment]
> I don't understand. If the AppVeyer CI doesn't have a URL

I misunderstood your question there. I though you wanted to know what URL AppVeyor was using to get the source. Here is what you want: https://www.appveyor.com/

> Please explain, in detail, what AppVeyer is, what it does, and how to use it.

I guess that https://www.appveyor.com/docs/ contains all the information you need.

**Comment by semmerson** [comment]
@ocefpaf I'm afraid that I don't know AppVeyer well enough to allow it access to my corporation's repositories.

**Comment by ocefpaf** [comment]
AppVeyor is **the** standard for Windows CI testing nowadays, but if you cannot grant access to your corporate repositories you can revert #47 then.

**Comment by semmerson** [comment]
The UDUNIT-2 package is one of several packages that the Unidata team has on GitHub. According to the AppVeyer website, it will configure webhooks for **every** project.

We don't want that.

Can the "New Project" procedure on AppVeyer be told to only configure **one** project?

**Comment by ocefpaf** [comment]
> @ocefpaf The UDUNIT-2 package is one of several packages that the Unidata team has on GitHub. According to the AppVeyer website, it will configure webhooks for every project.
We don't want that.
Can the "New Project" procedure on AppVeyer be told to only configure one project?

Not sure. I always granted th default permissions. You can probably get more info at: http://help.appveyor.com/discussions

**Comment by semmerson** [comment]
The UDUNITS-2 repository is  now configured to use AppVeyer.
